name: update-meta

on:

  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v5


      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"


      - name: Install
        run: |

          pip install playwright
          pip install gspread
          pip install oauth2client

          playwright install chromium


      - name: Run crawler
        run:

          python update_meta.py

        env:

          GOOGLE_CREDS:
            ${{ secrets.GOOGLE_CREDS }}